#!/bin/sh

exec > >(tee -i /home/site/LogFiles/post-merge.log) 2>&1

remote_repo="origin"

branch="main"

cd /home/site/wwwroot

git reset --hard $remote_repo/$branch

echo "Updating Laravel App..."
composer install --no-dev --prefer-dist --optimize-autoloader
php artisan migrate --force
php artisan db:seed --force
