[supervisord]
logfile = /tmp/supervisord.log
pidfile = /tmp/supervisord.pid
nodaemon=true
user=root

[program:nginx]
command=nginx -g "daemon off;"
pidfile=/run/nginx.pid
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-fpm]
command=php-fpm8.2 -F
pidfile=/run/php/php8.2-fpm.pid
stdout_logfile=/home/multi/LogFiles/php-fpm.log
stdout_logfile_maxbytes=2MB
stderr_logfile=/home/multi/LogFiles/php-fpm-error.log
stderr_logfile_maxbytes=2MB

[program:mencached]
command=memcached -m 128 -p 11211 -u multi -l 0.0.0.0
stdout_logfile=/home/multi/LogFiles/memcached.log
stdout_logfile_maxbytes=2MB
stderr_logfile=/home/multi/LogFiles/memcached-error.log
stderr_logfile_maxbytes=2MB